exports.downloader = require('./downloader')
exports.stalker = require('./stalker')
exports.fun = require('./fun')
exports.spammer = require('./spammer')
exports.nsfw = require('./nsfw')
exports.weeaboo = require('./weeaboo')
exports.misc = require('./misc')
exports.toxic = require('./toxic')